# GET root URL


GET https://cst8916-assignment-bcb9hye7b4bsa5hw.canadacentral-01.azurewebsites.net/
Accept: text/plain

###

# GET health check
GET https://cst8916-assignment-bcb9hye7b4bsa5hw.canadacentral-01.azurewebsites.net/health
Accept: application/json

###

# GET all users
GET https://cst8916-assignment-bcb9hye7b4bsa5hw.canadacentral-01.azurewebsites.net/users
Accept: application/json

###

# GET a specific user by ID
GET https://cst8916-assignment-bcb9hye7b4bsa5hw.canadacentral-01.azurewebsites.net/users/1
Accept: application/json

###

# POST create a new user
POST https://cst8916-assignment-bcb9hye7b4bsa5hw.canadacentral-01.azurewebsites.net/users
Content-Type: application/json

{
  "name": "Charlie",
  "age": 22
}

###

# PUT update a user by ID
PUT https://cst8916-assignment-bcb9hye7b4bsa5hw.canadacentral-01.azurewebsites.net/users/1
Content-Type: application/json

{
  "name": "Alice Updated",
  "age": 26
}

###

# DELETE a user by ID
DELETE https://cst8916-assignment-bcb9hye7b4bsa5hw.canadacentral-01.azurewebsites.net/users/1


###

# GET all tasks
GET https://cst8916-assignment-bcb9hye7b4bsa5hw.canadacentral-01.azurewebsites.net/tasks
Accept: application/json

###

# GET a specific task by ID
GET https://cst8916-assignment-bcb9hye7b4bsa5hw.canadacentral-01.azurewebsites.net/tasks/1
Accept: application/json

###

# GET a task that does not exist
GET https://cst8916-assignment-bcb9hye7b4bsa5hw.canadacentral-01.azurewebsites.net/tasks/5
Accept: application/json

###

# POST create a new task
POST https://cst8916-assignment-bcb9hye7b4bsa5hw.canadacentral-01.azurewebsites.net/tasks
Content-Type: application/json

{
  "title": "Complete assignment",
  "description": "Finish the REST API lab assignment",
  "user_id": 2,
  "completed": false
}

###

# POST create a new task with missing title
POST https://cst8916-assignment-bcb9hye7b4bsa5hw.canadacentral-01.azurewebsites.net/tasks
Content-Type: application/json

{
  "description": "Finish the REST API lab assignment",
  "user_id": 2,
  "completed": false
}

###

# POST create a new task with invalid user_id
POST https://cst8916-assignment-bcb9hye7b4bsa5hw.canadacentral-01.azurewebsites.net/tasks
Content-Type: application/json

{
  "title": "Complete assignment",
  "description": "Finish the REST API lab assignment",
  "user_id": 8,
  "completed": false
}

###

# PUT update a task by ID
PUT https://cst8916-assignment-bcb9hye7b4bsa5hw.canadacentral-01.azurewebsites.net/tasks/2
Content-Type: application/json

{
  "title": "Complete assignment updated",
  "description": "Finish the REST API lab assignment updated",
  "user_id": 1,
  "completed": true
}

###

# DELETE a task by ID
DELETE https://cst8916-assignment-bcb9hye7b4bsa5hw.canadacentral-01.azurewebsites.net/tasks/3

###

# GET all tasks for a specific user by user ID
GET https://cst8916-assignment-bcb9hye7b4bsa5hw.canadacentral-01.azurewebsites.net/users/1/tasks
Accept: application/json

###